spring:
  application:
    name: tlias-web-management

  # 数据库的连接信息
  datasource:

    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

# MyBatis 的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
